### PR TITLE
Multiple files windows zip

### PR DESCRIPTION
**Pull request by Jeff-Hanson**
In response to [issue 14 ](https://github.com/aws/aws-lambda-go/issues/96) this is an enhancement to support adding multiple files to a zip on windows using the build-lambda-zip tool.

### CODE REVIEW

**Comment by leepa** [comment]
Please don't include binaries in the repository, might be worst squashing/force pushing as well as you'll have to force push anyway.

**Comment by Jeff-Hanson** [comment]
OOPS, sorry about the binary. Should be removed now.

**Comment by bmoffatt** [comment]
I'm happy with this approach. This tool may now need a v2 revision when adding additional flags.

**Comment by ioannist** [comment]
Tried including a template file, but I am getting an error.

```
go build -o ..\dist\main main.go welcome.gohtml
named files must be .go files: welcome.gohtml
```

**Pull request merged**
