### PR TITLE
introduce reviewdog

### PR DESCRIPTION
**Pull request by shogo82148**
*Issue #, if available:*
N/A

*Description of changes:*

[golangci-lint](https://github.com/golangci/golangci-lint) is awesome linter, but It takes a lot of work to check the results on pull requests.
[reviewdog/action-golangci-lint](https://github.com/marketplace/actions/run-golangci-lint-with-reviewdog) provides better code review experience.
see [reviewdog](https://github.com/reviewdog/reviewdog) repo for more info.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by bmoffatt — CHANGES_REQUESTED** [review]
We should leave the `lint.yml` workflow as-is, and add a new `reviewdog.yml` to run side-by-side for comparison

**Comment by shogo82148** [comment]
done!
I added `reviewdog.yml`.

**Comment by harrisonhjones** [comment]
@bmoffatt any thoughts on this? Seems like a pretty easy win.

**Review by bmoffatt — APPROVED** [review]

**Comment by bmoffatt** [comment]
let's see what this looks like!

**Pull request merged**
