### PR TITLE
Add APIGatewayv2 Lambda Authorizer support in events

### PR DESCRIPTION
**Pull request by tjames-stig**
*Issue #, if available:*
This addresses #394, which really is more of a symptom of not having purpose-built struct definitions for authorizers for HTTP API Gateway.

*Description of changes:*
apigw.go did not have any purpose-built struct definitions available for use for apigatewayv2 HTTP Lambda Authorizers, so I've added struct definitions for the V1 and V2 payloads for apigatewayv2 Lambda Authorizer requests, as well as the IAM Policy response payload. 

I've tested the V2 request payload, as that is what I have code written in place for, but I have not yet tested the V1 request payload or the IAM policy response payload. For all struct definitions, I followed the documentation found at the [http api lambda authorizer documentation](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html).

I've attempted to reuse other structure definitions and follow what appeared to be the pre-existing naming convention for type names. I believe this is more or less what support for HTTP Lambda Authorizers should look like, but there will likely need to be some adjustments and tinkering made to naming and member ordering. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by menego** [comment]
@tjames-stig I see that the merge is blocked by a simple lint error, I hope you can find the time to fix it soon :-)

**Comment by tjames-stig** [comment]
This PR now passes my fork's workflows.

**Review by menego — APPROVED** [review]

**Comment by bmoffatt** [comment]
added the test data from https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-lambda-authorizer.html

**Comment by menego** [comment]
Hi guys, forgive my ignorance and sorry for asking here but what is the release cycle?
When should this feature be expected to be released?
Is there some doc explaining these?

**Comment by bmoffatt** [comment]
@menego I've just tagged v1.29.0, enjoy!

**Pull request merged**
