### PR TITLE
add iot button event

### PR DESCRIPTION
**Pull request by cofemei**
➜  events git:(add-iot-button-event) ✗ go test
PASS
ok  	aws-lambda-go/events	0.020s

### CODE REVIEW

**Comment by cofemei** [comment]
done,

**Comment by bmoffatt** [comment]
had to rebase the commits onto 1ff6c543cd609ee607904670f871e8a4cfdd954a to get the travis build to pass.

Thanks!

**Comment by stephbu** [comment]
Hey Bryan, thanks for merging in the IoTButtonEvent struct/deserializer.  Using deps at the moment, and pulling from the head of master branch sucks :(  Wondering when that will get packaged into a release?

**Comment by bmoffatt** [comment]
@stephbu i've tagged HEAD as v1.7.0

**Pull request merged**
