### PR TITLE
Provide cloudwatch logs event, parse for content

### PR DESCRIPTION
**Pull request by jspc**
This pull request implements a cloudwatch logs event and provides tests and documentation strings.

Additionally will, when asked, parse the base64'd gzipped log data into a log entry.

### CODE REVIEW

**Comment by bmoffatt** [comment]
Thanks for the PR. I'm going to take a closer look at this before pulling. The equivalent in our .NET and Java Libraries don't provide the

**Comment by jspc** [comment]
Yeah, I was hesitant to add it because I can't see it in the other libraries. I decided to whack it in anyway- everyone's code to parse these entries will look damn near identical to this, and in the PR it's more of a helper than anything.

In the end I erred on the side of helpfulness and decided that if other libraries didn't have it that didn't mean that it wasn't useless. Especially since the code is all stdlib.

**Comment by bmoffatt** [comment]
Thanks for the PR. I'm going to take a closer look at what CloudWatch sends before pulling, since the equivalent class in the Java and .NET libraries didn't opt to include the unmarshaling of the `awslogs` data. 

* https://github.com/aws/aws-lambda-dotnet/blob/master/Libraries/src/Amazon.Lambda.CloudWatchLogsEvents/CloudWatchLogsEvents.cs 
* https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/CloudWatchLogsEvent.java

**Comment by bmoffatt** [comment]
I can pull this if you remove the helper. You can create another pull request to add the helper as well, it looks useful, but I want to first reach out to a member of the CloudWatch Logs team to discuss the structure in the encoded blob.

**Comment by jspc** [comment]
@bmoffatt ♻️ 

I've removed helper code and tests, leaving known structs and tests for them.

I'll open a PR this morning for the helpers. What can I do to help get confirmation from someone in Cloudwatch Logs? Can I do anything?

**Comment by bmoffatt** [comment]
>  What can I do to help get confirmation 

Include any links to public documentation you come across in the other PR.

**Pull request merged**
