### PR TITLE
[BREAKING CHANGE] Clean up CodePipeline Job Implementation

### PR DESCRIPTION
**Pull request by whithajess**
* Incorrectly used "CodePipelineEvent"

*Issue #, if available:*

#244

*Description of changes:*

Moves `CodePipelineJob` into its own `CodePipelineJobEvent` giving back the `CodePipelineEvent` namespace for actual usage.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by whithajess** [comment]
@bmoffatt Did you have any thoughts on this? Thanks.

**Comment by bmoffatt** [comment]
> @bmoffatt Did you have any thoughts on this? Thanks.

I'd rather not do a semver-major change. I'm ok with adding and alias `type CodePipelineEvent = CodePipelineJobEvent` to help with the ambiguity.

**Comment by whithajess** [comment]
@bmoffatt I understand the reluctance for a `semver-major` but this will trip a lot of people up in the future even with the alias, it breaks the principle of least surprise all the other Events are what they say they are. This is what I did originally - Assumed that `CodePipelineEvent` was the same as `CodeBuildEvent` and then when digging in found that `CodePipelineEvent` was something completely unexpected!

**Comment by bmoffatt** [comment]
We won't be merging intentionally breaking changes at this time. I've tagged #244 as requiring a v2 release to keep track of the request.

For #247, a different type name can be used.

**Pull request closed without merging**
