### PR TITLE
remove dialog action from lex event

### PR DESCRIPTION
**Pull request by artempanko**
Remove DialogAction from LexEvent according to https://docs.aws.amazon.com/lex/latest/dg/lambda-input-response-format.html#using-lambda-input-event-format and align tests with LexResponse model.

### CODE REVIEW

**Comment by artempanko** [comment]
@bmoffatt, please review

**Comment by diegobernardes** [comment]
Hi @artempanko, thanks for this contribution. We're discussing how we can proceed with this kind of request as it breaks our API compatibility. The next major version should fix all this issues at once.

**Comment by bmoffatt** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: aws-lambda-go-github-ci
* Commit ID: 44d5f64bd623a6f34e7aa47606b6f95bfdd1b4e7
* Result: SUCCEEDED
* [Build Logs](https://yxbry9e1t8.execute-api.us-east-1.amazonaws.com/Prod/buildlogs?key=c35acd5a-66bc-41ce-81f7-4e30392b37ed%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by bmoffatt** [comment]
rebased and added a deprecation comment that linters will complain about rather than removing the field

**Review by bmoffatt — APPROVED** [review]

**Pull request merged**
