### PR TITLE
Add AppSync direct resolver type

### PR DESCRIPTION
**Pull request by ThomasP1988**
*Issue #, if available:*

Appsync direct lambda resolver type

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bmoffatt** [comment]
looks like a duplicate of https://github.com/aws/aws-lambda-go/pull/465 - can you confirm if it's for the same integration? A link to the matching AWS docs for the feature would help clarify

**Comment by ThomasP1988** [comment]
Yes it is, took in consideration your change requests in other pull request but wanted to speed up the process as it seems inactive

**Comment by ThomasP1988** [comment]
what is the test payload ?

**Comment by bmoffatt** [comment]
> what is the test payload ?

https://github.com/aws/aws-lambda-go/pull/465/files#diff-87ea17b18acd388d251c932deae93ba9986ac92a15fe79335d6bc7b043eac6a3

**Pull request closed without merging**
